---
# tasks file for bareos-client
- include: centos7.yml
  when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" )

- include: centos6.yml
  when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" )

- include: opensuse13.yml
  when: ( ansible_distribution == "openSUSE" and ansible_distribution_major_version == "13" )

- include: ubuntu14.yml
  when: ( ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04" )

- include: ubuntu12.yml
  when: ( ansible_distribution == "Ubuntu" and ansible_distribution_version == "12.04" )
