- name: "| BAREOS Ubuntu12.04 | Add bareos repo"
  copy: src=files/ubuntu12.repo dest=/etc/apt/sources.list.d/bareos.list
  notify:  add bareos repo key

- name: "| BAREOS Ubuntu12.04 | add repo key"
  apt_key: url=http://download.bareos.org/bareos/contrib/xUbuntu_12.04/Release.key state=present

- name: "| BAREOS Ubuntu12.04 | Install bareos fd"
  apt: name=bareos-client state=latest update_cache=yes allow_unauthenticated=yes
  notify: enable bareos-fd

- name: "| BAREOS Ubuntu12.04 | Add configuration to bareos-fd"
  template: src=templates/bareos-fd.j2 dest=/etc/bareos/bareos-fd.conf force=yes
  notify: 
  - restart bareos-fd

- name: "| BAREOS Ubuntu12.04 | Add configuration to bareos-dir"
  delegate_to: "{{ bareos_director }}"
  template: src=templates/bareos-dir.j2 dest=/etc/bareos/clientdefs/{{ ansible_hostname }}.conf force=yes
  when: "{{ bareos_setup_dir }}"

- name: "| BREAOS Ubuntu12.04 | Add include client conf to director"
  delegate_to: "{{ bareos_director }}"
  lineinfile: dest=/etc/bareos/bareos-dir.conf line="@/etc/bareos/clientdefs/{{ ansible_hostname }}.conf"
  notify: reload bareos-dir
  when: "{{ bareos_setup_dir }}"
