- name: "| BAREOS | Add bareos repo"
  copy: src=files/ubuntu14.repo dest=/etc/apt/sources.list.d/bareos.list
  when: ( ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" )
  notify:  add bareos repo key

- name: "| BAREOS  | add repo key"
  apt_key: url=http://download.bareos.org/bareos/contrib/xUbuntu_14.04/Release.key state=present

- name: "| BAREOS | Install bareos fd"
  apt: name=bareos-client state=latest update_cache=yes allow_unauthenticated=yes
  when: ( ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" )
  notify: enable bareos-fd

- name: "| BAREOS | Add configuration to bareos-fd"
  template: src=templates/bareos-fd.j2 dest=/etc/bareos/bareos-fd.conf force=yes
  when: ( ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" )
  notify: restart bareos-fd

- name: "| BAREOS | Add configuration to director"
  delegate_to: "{{ bareos_director }}"
  template: src=templates/bareos-dir.j2 dest=/etc/bareos/clientdefs/{{ ansible_hostname }}.conf force=yes

- name: "| BAREOS | Include conf to director"
  delegate_to: "{{ bareos_director }}"
  lineinfile: dest=/etc/bareos/bareos-dir.conf line="@/etc/bareos/clientdefs/{{ ansible_hostname }}.conf"
  notify: reload bareos-dir
